### ISSUE TITLE
Filename for DOT contains the whole file?

### ISSUE THREAD

**Issue by l3nz** [l3nz/say_cheez_ex#34]
```
== Compilation error in file lib/logfwd/teams/call_timeline.ex ==
** (File.Error) could not write to file "/var/folders/ct/yzb4gg552qqbgwdq48y2jcph0000gn/T/SayCheezImg_gv_digraph {\n  new -> AA;\n  new -> CQ;\n  new -> Voicemail;\n  AA -> AA;\n  AA -> CQ;\n  CQ -> RNA [label=\"x\"; style=\"dotted\"];\n  RNA -> CQ;\n  CQ -> Agent;\n  Agent -> MOH [label=\"x\"; style=\"dotted\"];\n  MOH -> Agent;\n  CQ -> new;\n  Agent -> new;\n  new -> Direct;\n  Direct -> new;\n}\n": file name too long
    (elixir 1.14.3) lib/file.ex:1104: File.write!/3
    (say_cheez_ex 0.3.5) lib/graphs/graphviz.ex:25: SayCheezEx.Graphs.Graphviz.generate_content_graphviz_local/1
    (say_cheez_ex 0.3.5) lib/graphs/provider.ex:62: SayCheezEx.Graphs.Provider.rebuild_if_needed/3
    (say_cheez_ex 0.3.5) lib/graphs/graphviz.ex:13: SayCheezEx.Graphs.Graphviz.render!/1
    lib/logfwd/teams/call_timeline.ex:812: (module)
    (elixir 1.14.3) lib/kernel/parallel_compiler.ex:340: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```

A Hash would be enough....

**Comment by l3nz** [comment]
See https://github.com/l3nz/say_cheez_ex/blob/1f4f6edf89ad3b8fc6ac98ce2260cbd646c6aa6e/lib/graphs/provider.ex#L114
